services:
  fair-online-web:
    image: ${FAIR_ONLINE_WEB_IMAGE:-ghcr.io/rj9676564/fair-online-web}:${FAIR_ONLINE_IMAGE_TAG:-latest}
    depends_on:
      - fair-online-service
    environment:
      FAIR_ONLINE_API_BASE_URL: ${FAIR_ONLINE_API_BASE_URL:-/service/}
      FAIR_ONLINE_SERVICE_PROXY_PASS: http://fair-online-service:8082
      FAIR_ONLINE_RESOURCE_PROXY_PASS: http://fair-online-service:8002
      FAIR_ONLINE_BACKEND_WEB_PROXY_PASS: http://fair-online-service:8001
    ports:
      - "${FAIR_ONLINE_PORT:-8080}:80"
    restart: unless-stopped

  fair-online-service:
    image: ${FAIR_ONLINE_SERVICE_IMAGE:-ghcr.io/rj9676564/fair-online-service}:${FAIR_ONLINE_IMAGE_TAG:-latest}
    environment:
      FAIR_ONLINE_RESOURCE_BASE_URL: ${FAIR_ONLINE_RESOURCE_BASE_URL:-/resource}
    expose:
      - "8082"
      - "8001"
      - "8002"
    restart: unless-stopped
    volumes:
      - fair-online-user-project:/app/fairDir/userProject

volumes:
  fair-online-user-project:
