services:
  fair-online-web:
    build:
      context: ./fair_online
    depends_on:
      - fair-online-service
    environment:
      FAIR_ONLINE_API_BASE_URL: ${FAIR_ONLINE_API_BASE_URL:-/service/}
      FAIR_ONLINE_SERVICE_PROXY_PASS: http://fair-online-service:8082/
      FAIR_ONLINE_RESOURCE_PROXY_PASS: http://fair-online-service:8002/
      FAIR_ONLINE_BACKEND_WEB_PROXY_PASS: http://fair-online-service:8001/
    ports:
      - "${FAIR_ONLINE_PORT:-8080}:80"
    restart: unless-stopped

  fair-online-service:
    build:
      context: ./fair_online_service
    environment:
      FAIR_ONLINE_RESOURCE_BASE_URL: ${FAIR_ONLINE_RESOURCE_BASE_URL:-/resource}
    expose:
      - "8082"
      - "8001"
      - "8002"
    restart: unless-stopped
    volumes:
      - fair-online-user-project:/app/fairDir/userProject

volumes:
  fair-online-user-project:
